"use client"
import { SessionProvider } from 'next-auth/react'
import './globals.css'
import Providers from '@/components/Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
          <SessionProvider>
        <Providers>
          {children}
        </Providers>
        </SessionProvider>
  )
}
